ror_api/config/routes.rb
Rails.application.routes.draw do

  root to: 'test2#index'

  devise_for :users

  get 'test2', to: 'test2#index'

  resources :roles
  resources :permissions

  namespace :api do
    post 'get_countries_by_ip/', to: 'ip_api#get_countries'
  end
end

ror_api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ror_api/app/models/permission.rb
class Permission < ApplicationRecord
  has_and_belongs_to_many :roles
end

ror_api/app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions
end

ror_api/app/models/user.rb
class User < ApplicationRecord

  ROLE_ADMIN = 'admin'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :trackable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :roles

  def admin?
    self.roles.select { |role| role.name == ROLE_ADMIN}.any?
  end
end

ror_api/app/controllers/api/ip_api_controller.rb
class Api::IpApiController < ApplicationController
  skip_before_action :verify_authenticity_token

  def get_countries
    addresses = IpApiService.new.get_countries_ips(params[:addresses])

    # there is caching for example, but in this case it doesn't make sense,
    # because i don't save or attach to response key of cache
    key = SecureRandom.urlsafe_base64
    Rails.cache.fetch(key, expires_in: 12.hours) {addresses}

    render json: addresses.compact
  end
end

ror_api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:warning] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

ror_api/app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController

  before_action -> { authorize Permission }
  before_action :set_permission, only: [:update, :edit, :destroy]
  def index
  end

  def new
    @permission = Permission.new
    authorize @permission
    @permission
  end

  def create
    @permission = Permission.new(permission_params)
    authorize @permission

    if @permission.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def set_permission
    @permission = Permission.find(params[:id])
  end

  def permission_params
    params.require(:permission).permit(:name)
  end
end

ror_api/app/controllers/roles_controller.rb
class RolesController < ApplicationController

  before_action -> { authorize Role }
  before_action :set_role, only: [:update, :edit, :destroy]
  def index
  end

  def new
    @role = Role.new
    authorize @role
    @role
  end

  def create
    @role = Role.new(role_params)
    authorize @role

    if @role.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def set_role
    @role = Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:name)
  end
end

ror_api/app/controllers/test2_controller.rb
class Test2Controller < ApplicationController

  before_action :authenticate_user!

  def index
    if @roles = current_user.roles
      @roles
    end
  end
end

ror_api/app/helpers/application_helper.rb
module ApplicationHelper
end

ror_api/app/helpers/ip_api_helper.rb
module IpApiHelper
end

ror_api/app/helpers/test_2_helper.rb
module Test2Helper
end

ror_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ror_api/app/views/permissions/new.erb
<h1>New permission</h1>
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<% end %>
<%= form_for @permission, url: permissions_path, local: true do |form| %>
    <p>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

ror_api/app/views/roles/new.erb
<h1>New role</h1>
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<% end %>
<%= form_for @role, url: roles_path, local: true do |form| %>
    <p>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

ror_api/app/views/test2/index.erb
<% if user_signed_in? %>
    <h1>Hello <%=  current_user.email %></h1>
    <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
    <% @roles.each do |role|%>
      <h2><%= role.name %></h2>
        <% role.permissions.each do |permission|%>
            <p style="margin-left: 50px"><%= permission.name %></p>
        <% end %>
    <% end %>
    <div><%= link_to 'Add new role', new_role_path %></div>
    <div><%= link_to 'Add new permission', new_permission_path %></div>
<% end %>